apiVersion: v1
kind: Pod
metadata:
  name: sleepy-volta
  namespace: bmebootcamp
  labels: {app: nextflow, runName: sleepy-volta}
spec:
  restartPolicy: Never
  containers:
  - name: sleepy-volta
    image: nextflow/nextflow:20.07.1
    command: [/bin/bash, -c, source /etc/nextflow/init.sh; nextflow run vpeddu/kube_prp_test
        -name sleepy-volta -latest true]
    env:
    - {name: NXF_WORK, value: /tmp/vikas/work}
    - {name: NXF_ASSETS, value: /tmp/projects}
    - {name: NXF_EXECUTOR, value: k8s}
    - {name: NXF_ANSI_LOG, value: 'false'}
    volumeMounts:
    - {name: vol-1, mountPath: /tmp}
    - {name: vol-2, mountPath: /etc/nextflow}
  volumes:
  - name: vol-1
    persistentVolumeClaim: {claimName: vikas-ucsc-pvc}
  - name: vol-2
    configMap: {name: nf-config-cc0f2a42}
